const it = [
  {
    id: 1,
    name: "Colosseum",
    country: "Italy",
    category: "Architecture",
    tags: ["ancient", "amphitheater", "Rome"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Colosseum, also known as the Flavian Amphitheatre, is an iconic symbol of Rome. It was built in AD 70-80 and could hold up to 80,000 spectators for gladiatorial contests and public spectacles.",
  },
  {
    id: 2,
    name: "Vatican City",
    country: "Italy",
    category: "Religion",
    tags: ["papal", "museums", "Sistine Chapel"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Vatican City is the smallest independent state in the world and serves as the spiritual center for the Roman Catholic Church. It is home to St. Peter's Basilica and the Sistine Chapel, famous for Michelangelo's ceiling.",
  },
  {
    id: 3,
    name: "Florence",
    country: "Italy",
    category: "Culture",
    tags: ["Renaissance", "art", "Duomo"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Florence is known as the birthplace of the Renaissance and is famous for its art, architecture, and cultural heritage. The Florence Cathedral, with its iconic dome designed by Brunelleschi, dominates the skyline.",
  },
  {
    id: 4,
    name: "Venice",
    country: "Italy",
    category: "Adventure",
    tags: ["canals", "gondolas", "Grand Canal"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Venice is a unique city built on a network of canals and is renowned for its beautiful architecture and romantic gondola rides. The Grand Canal is lined with stunning palaces and historic buildings.",
  },
  {
    id: 5,
    name: "Amalfi Coast",
    country: "Italy",
    category: "Nature",
    tags: ["coastal", "scenic", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Amalfi Coast is a stunning stretch of coastline known for its picturesque villages, dramatic cliffs, and crystal-clear waters. It is a UNESCO World Heritage site and a popular destination for travelers.",
  },
  {
    id: 6,
    name: "Leaning Tower of Pisa",
    country: "Italy",
    category: "Architecture",
    tags: ["tower", "landmark", "Pisa"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Leaning Tower of Pisa is famous for its unintended tilt. Completed in the 14th century, this freestanding bell tower is part of the cathedral complex in Pisa and attracts millions of visitors each year.",
  },
  {
    id: 7,
    name: "Pompeii",
    country: "Italy",
    category: "History",
    tags: ["archaeological site", "volcano", "Naples"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Pompeii was an ancient Roman city that was buried under volcanic ash from Mount Vesuvius in AD 79. The site provides insight into Roman life and has been remarkably preserved, making it a major archaeological site.",
  },
  {
    id: 8,
    name: "Cinque Terre",
    country: "Italy",
    category: "Nature",
    tags: ["coastal villages", "hiking"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Cinque Terre consists of five charming coastal villages along the Italian Riviera. Known for their colorful houses and stunning sea views, these villages are popular for hiking and exploring picturesque landscapes.",
  },
  {
   id: 9,
   name: "Tuscany",
   country: "Italy",
   category: "Nature",
   tags: ["vineyards", "countryside", "wine"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Tuscany is famous for its rolling hills, vineyards, and olive groves. This region is known for producing some of Italy's finest wines and offers beautiful landscapes that have inspired artists for centuries.",
  },
  {
   id: 10,
   name:"Duomo di Milano",
   country:"Italy",
   category:"Architecture",
   tags:["cathedral","Gothic","Milan"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"The Duomo di Milano is one of the largest cathedrals in Europe, known for its stunning Gothic architecture. Construction began in the late 14th century and features intricate sculptures and beautiful stained glass windows.",
  },
];

export default it;
