const ind = [
  {
    id: 1,
    name: "Taj Mahal",
    country: "India",
    category: "Architecture",
    tags: ["monument", "marble", "world heritage"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Taj Mahal is a stunning white marble mausoleum built in memory of Mumtaz Mahal, the wife of Mughal Emperor Shah Jahan. It is a UNESCO World Heritage Site and a symbol of love.",
  },
  {
    id: 2,
    name: "Jaipur City Palace",
    country: "India",
    category: "History",
    tags: ["palace", "culture", "heritage"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Jaipur City Palace is a magnificent complex that showcases a blend of Rajput and Mughal architecture. It serves as a museum and is still the residence of the royal family.",
  },
  {
    id: 3,
    name: "Qutub Minar",
    country: "India",
    category: "Architecture",
    tags: ["minar", "history", "landmark"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Qutub Minar is the tallest brick minaret in the world, standing at 73 meters. It was built in the 12th century and is part of the Qutub complex, a UNESCO World Heritage Site.",
  },
  {
    id: 4,
    name: "Varanasi Ghats",
    country: "India",
    category: "Religion",
    tags: ["temples", "spirituality", "Ganges"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Varanasi Ghats are a series of steps leading to the Ganges River, where pilgrims perform rituals and ceremonies. It is one of the holiest cities in Hinduism.",
  },
  {
    id: 5,
    name: "Manali",
    country: "India",
    category: "Nature",
    tags: ["mountains", "snow", "adventure"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Manali is a popular hill station known for its stunning landscapes, adventure sports, and as a gateway to the Solang Valley and Rohtang Pass.",
  },
  {
    id: 6,
    name: "Ranthambore National Park",
    country: "India",
    category: "Wildlife",
    tags: ["tigers", "safari", "nature"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Ranthambore National Park is one of the largest national parks in India, famous for its Bengal tiger population and diverse wildlife. It offers exciting safari experiences.",
  },
  {
    id: 7,
    name: "Hampi",
    country: "India",
    category: "History",
    tags: ["ruins", "temples", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Hampi is a UNESCO World Heritage Site known for its ancient temples, ruins, and stunning landscapes. It was once the capital of the Vijayanagara Empire.",
  },
  {
    id: 8,
    name: "Golden Temple",
    country: "India",
    category: "Religion",
    tags: ["temple", "sikh", "peace"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Golden Temple, or Harmandir Sahib, is the holiest Gurdwara of Sikhism located in Amritsar. It is known for its stunning gold-plated dome and serene atmosphere.",
  },
  {
   id: 9,
   name:"Mysore Palace",
   country:"India",
   category:"History",
   tags:["palace","architecture","royalty"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Mysore Palace is an architectural marvel that showcases Indo-Saracenic style. It serves as the residence of the Wadiyar dynasty and hosts the famous Dussehra festival.",
  },
  {
   id: 10,
   name:"Rishikesh",
   country:"India",
   category:"Adventure",
   tags:["rafting","yoga","Ganges"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Rishikesh, known as the 'Yoga Capital of the World', offers spiritual retreats and adventure activities like white-water rafting along the Ganges River.",
  },
  {
   id: 11,
   name:"Jaisalmer Fort",
   country:"India",
   category:"History",
   tags:["fort","sandstone","desert"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Jaisalmer Fort, also known as Sonar Quila or Golden Fort, is a UNESCO World Heritage Site made of yellow sandstone that appears golden in color during sunset.",
  },
  {
   id: 12,
   name:"Leh Ladakh",
   country:"India",
   category:"Adventure",
   tags:["mountains","biking","scenic"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Leh Ladakh is known for its breathtaking landscapes, high-altitude lakes, and adventure activities like trekking and biking through rugged terrains.",
  },

 // Continue this pattern for any additional entries...

];

export default ind;
