const rus = [
  {
    id: 1,
    name: "Red Square",
    country: "Russia",
    category: "Architecture",
    tags: ["historical", "landmark", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Red Square is a famous city square in Moscow, known for its historical significance and as a UNESCO World Heritage Site. It is surrounded by iconic buildings like the Kremlin and Saint Basil's Cathedral.",
  },
  {
    id: 2,
    name: "The Kremlin",
    country: "Russia",
    category: "History",
    tags: ["fortress", "government", "architecture"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Kremlin is a fortified complex in the heart of Moscow, serving as the official residence of the President of Russia. It features stunning architecture and rich history.",
  },
  {
    id: 3,
    name: "Saint Basil's Cathedral",
    country: "Russia",
    category: "Architecture",
    tags: ["cathedral", "onion domes", "iconic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Saint Basil's Cathedral is an iconic symbol of Russia, known for its colorful onion domes. It was built in the 16th century and is located on Red Square.",
  },
  {
    id: 4,
    name: "Hermitage Museum",
    country: "Russia",
    category: "Culture",
    tags: ["museum", "art", "history"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Hermitage Museum in Saint Petersburg is one of the largest and oldest museums in the world, housing an extensive collection of art and cultural artifacts.",
  },
  {
    id: 5,
    name: "Lake Baikal",
    country: "Russia",
    category: "Nature",
    tags: ["lake", "deepest", "scenic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Lake Baikal is the world's deepest and oldest freshwater lake, known for its stunning natural beauty and diverse wildlife. It is a UNESCO World Heritage Site.",
  },
  {
    id: 6,
    name: "Peterhof Palace",
    country: "Russia",
    category: "Architecture",
    tags: ["palace", "gardens", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Peterhof Palace, often referred to as the 'Russian Versailles', is famous for its beautiful gardens and fountains. It was commissioned by Peter the Great in the early 18th century.",
  },
  {
    id: 7,
    name: "Catherine Palace",
    country: "Russia",
    category: "History",
    tags: ["palace", "baroque", "heritage"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Catherine Palace is a stunning example of Baroque architecture located near Saint Petersburg. It was the summer residence of the Russian tsars and features opulent interiors.",
  },
  {
    id: 8,
    name: "Trans-Siberian Railway",
    country: "Russia",
    category: "Adventure",
    tags: ["train journey", "scenic", "historic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Trans-Siberian Railway is one of the longest railway lines in the world, connecting Moscow to Vladivostok. It offers breathtaking views of Russia's diverse landscapes.",
  },
  {
   id: 9,
   name:"Kizhi Island",
   country:"Russia",
   category:"Culture",
   tags:["UNESCO","wooden architecture"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Kizhi Island is renowned for its unique wooden architecture, including the famous Church of the Transfiguration. It is a UNESCO World Heritage Site located on Lake Onega.",
  },
  {
   id: 10,
   name:"Sochi",
   country:"Russia",
   category:"Nature",
   tags:["beach","resort","Black Sea"],
   image:"https://dummyimage.com/600x400/000/fff",
   desc:"Sochi is a popular resort city on the Black Sea, known for its beaches, mild climate, and as a host city for the Winter Olympics in 2014.",
  },
];

export default rus;
