const us = [
  // USA
  {
    id: 1,
    name: "Statue of Liberty",
    country: "USA",
    category: "Landmark",
    tags: ["historical", "symbol", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, a symbol of freedom and democracy.",
  },
  {
    id: 2,
    name: "Golden Gate Bridge",
    country: "USA",
    category: "Architecture",
    tags: ["iconic", "suspension bridge", "scenic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "An iconic suspension bridge connecting San Francisco to Marin County, known for its stunning views.",
  },
  {
    id: 3,
    name: "Mount Rushmore",
    country: "USA",
    category: "Monument",
    tags: ["historical", "sculpture", "national memorial"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Features the sculpted heads of four U.S. presidents carved into granite in South Dakota.",
  },
  {
    id: 4,
    name: "Grand Canyon",
    country: "USA",
    category: "Nature",
    tags: ["canyon", "national park", "scenic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "One of the world’s most awe-inspiring natural wonders located in Arizona.",
  },
  {
    id: 5,
    name: "White House",
    country: "USA",
    category: "Government",
    tags: ["historical", "residence", "symbol"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The official residence and workplace of the President of the United States in Washington D.C.",
  },

  // Germany
  {
    id: 6,
    name: "Brandenburg Gate",
    country: "Germany",
    category: "Landmark",
    tags: ["historical", "symbol", "architecture"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "An 18th-century neoclassical monument in Berlin symbolizing peace and unity.",
  },
  {
    id: 7,
    name: "Neuschwanstein Castle",
    country: "Germany",
    category: "Architecture",
    tags: ["castle", "fairytale", "tourist attraction"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A picturesque castle in Bavaria known for its romantic architecture.",
  },
  {
    id: 8,
    name: "Cologne Cathedral",
    country: "Germany",
    category: "Architecture",
    tags: ["gothic", "UNESCO", "landmark"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A stunning example of Gothic architecture and a UNESCO World Heritage Site.",
  },
  {
    id: 9,
    name: "Berlin Wall Memorial",
    country: "Germany",
    category: "Historical Site",
    tags: ["memorial", "history", "landmark"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A preserved section of the Berlin Wall that commemorates the division of East and West Berlin.",
  },
  {
    id: 10,
    name: "Oktoberfest",
    country: "Germany",
    category: "Festival",
    tags: ["cultural", "beer festival", "tradition"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The world's largest beer festival held annually in Munich celebrating Bavarian culture.",
  },

  // Australia
  {
    id: 11,
    name: "Sydney Opera House",
    country: "Australia",
    category: "Architecture",
    tags: ["iconic", "performing arts", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A multi-venue performing arts center known for its unique shell-like design.",
  },
  {
    id: 12,
    name: "Great Barrier Reef",
    country: "Australia",
    category: "Nature",
    tags: ["coral reef", "marine life", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The world's largest coral reef system located off the coast of Queensland.",
  },
  {
    id: 13,
    name: "Uluru (Ayers Rock)",
    country: "Australia",
    category: "Natural Landmark",
    tags: ["sacred site", "geology", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A massive sandstone monolith in the heart of the Northern Territory's arid 'Red Centre.'",
  },
  {
    id: 14,
    name: "Bondi Beach",
    country: "Australia",
    category: "Beach",
    tags: ["surfing", "leisure", "iconic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A famous beach in Sydney known for its surf culture and vibrant atmosphere.",
  },
  {
    id: 15,
    name: "Daintree Rainforest",
    country: "Australia",
    category: "Nature",
    tags: ["rainforest", "biodiversity", "UNESCO"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "One of the oldest rainforests in the world located in Queensland with rich biodiversity.",
  },

  // Canada
  {
    id: 16,
    name: "CN Tower",
    country: "Canada",
    category: "Landmark",
    tags: ["tower", "observation", "iconic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A communications and observation tower in Toronto recognized as one of the tallest freestanding structures in the world.",
  },
  {
    id: 17,
    name: "Banff National Park",
    country: "Canada",
    category: "Nature",
    tags: ["national park", "mountains", "scenic"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "Canada’s first national park located in the Rocky Mountains known for its stunning landscapes and outdoor activities.",
  },
  {
    id: 18,
    name: "Niagara Falls",
    country: "Canada",
    category: "Natural Wonder",
    tags: ["waterfall", "scenic", "tourist attraction"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A group of three waterfalls located on the border between Canada and the USA known for their beauty and power.",
  },
  {
    id: 19,
    name: "Parliament Hill",
    country: "Canada",
    category: "Government",
    tags: ["historical site", "architecture"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "The seat of Canada's federal government located in Ottawa featuring stunning Gothic Revival architecture.",
  },
  {
    id: 20,
    name: "Old Quebec City",
    country: "Canada",
    category: "Historical Site",
    tags: ["UNESCO World Heritage Site"],
    image: "https://dummyimage.com/600x400/000/fff",
    desc: "A historic district featuring cobblestone streets and well-preserved buildings from the French colonial era.",
  },
];

export default us;
