const rus = [
  {
    id: 1,
    name: "Red Square",
    country: "Russia",
    category: "Architecture",
    tags: ["historical", "landmark", "UNESCO"],
    image: "https://images.unsplash.com/photo-1562903793-3af4a5f0e3f5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cmVkJTIwc3F1YXJlJTJDcnVzc2lhfGVufDB8fDB8fHww",
    desc: "Red Square is a famous city square in Moscow, known for its historical significance and as a UNESCO World Heritage Site. It is surrounded by iconic buildings like the Kremlin and Saint Basil's Cathedral.",
  },
  {
    id: 2,
    name: "The Kremlin",
    country: "Russia",
    category: "History",
    tags: ["fortress", "government", "architecture"],
    image: "https://images.unsplash.com/photo-1547448415-e9f5b28e570d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGhlJTIwa3JlbWxpbnxlbnwwfHwwfHx8MA%3D%3D",
    desc: "The Kremlin is a fortified complex in the heart of Moscow, serving as the official residence of the President of Russia. It features stunning architecture and rich history.",
  },
  {
    id: 3,
    name: "Saint Basil's Cathedral",
    country: "Russia",
    category: "Architecture",
    tags: ["cathedral", "onion domes", "iconic"],
    image: "https://images.unsplash.com/photo-1680019581276-da5931fe3b2e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjJ8fHNhaW50JTIwYmFzaWwncyUyMGNhdGhlZHJhbHxlbnwwfHwwfHx8MA%3D%3D",
    desc: "Saint Basil's Cathedral is an iconic symbol of Russia, known for its colorful onion domes. It was built in the 16th century and is located on Red Square.",
  },
  {
    id: 4,
    name: "Hermitage Museum",
    country: "Russia",
    category: "Culture",
    tags: ["museum", "art", "history"],
    image: "https://images.unsplash.com/photo-1609192604404-8574f77e5f5a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aGVybWl0YWdlJTIwbXVzZXVtfGVufDB8fDB8fHww",
    desc: "The Hermitage Museum in Saint Petersburg is one of the largest and oldest museums in the world, housing an extensive collection of art and cultural artifacts.",
  },
  {
    id: 5,
    name: "Lake Baikal",
    country: "Russia",
    category: "Nature",
    tags: ["lake", "deepest", "scenic"],
    image: "https://images.unsplash.com/photo-1650003818191-306e2b5a4784?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGFrZSUyMGJhaWthbCUyQ3J1c3NpYXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "Lake Baikal is the world's deepest and oldest freshwater lake, known for its stunning natural beauty and diverse wildlife. It is a UNESCO World Heritage Site.",
  },
  {
    id: 6,
    name: "Peterhof Palace",
    country: "Russia",
    category: "Architecture",
    tags: ["palace", "gardens", "UNESCO"],
    image: "https://images.unsplash.com/photo-1628698944211-fdcc2970398d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8cGV0ZXJob2YlMjBwYWxhY2V8ZW58MHx8MHx8fDA%3D",
    desc: "Peterhof Palace, often referred to as the 'Russian Versailles', is famous for its beautiful gardens and fountains. It was commissioned by Peter the Great in the early 18th century.",
  },
  {
    id: 7,
    name: "Catherine Palace",
    country: "Russia",
    category: "History",
    tags: ["palace", "baroque", "heritage"],
    image: "https://plus.unsplash.com/premium_photo-1661962571049-792ae9be2d79?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2F0aGVyaW5lJTIwcGFsYWNlfGVufDB8fDB8fHww",
    desc: "Catherine Palace is a stunning example of Baroque architecture located near Saint Petersburg. It was the summer residence of the Russian tsars and features opulent interiors.",
  },
  {
    id: 8,
    name: "Trans-Siberian Railway",
    country: "Russia",
    category: "Adventure",
    tags: ["train journey", "scenic", "historic"],
    image: "https://plus.unsplash.com/premium_photo-1661962378720-eb0c26b7f928?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fHRyYW5zJTIwJTIwc2liZXJpYW4lMjByYWlsd2F5fGVufDB8fDB8fHww",
    desc: "The Trans-Siberian Railway is one of the longest railway lines in the world, connecting Moscow to Vladivostok. It offers breathtaking views of Russia's diverse landscapes.",
  },
  {
   id: 9,
   name:"Kizhi Island",
   country:"Russia",
   category:"Culture",
   tags:["UNESCO","wooden architecture"],
   image:"https://plus.unsplash.com/premium_photo-1733266829433-6306cbd53e56?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGtpemhpJTIwaXNsYW5kfGVufDB8fDB8fHww",
   desc:"Kizhi Island is renowned for its unique wooden architecture, including the famous Church of the Transfiguration. It is a UNESCO World Heritage Site located on Lake Onega.",
  },
  {
   id: 10,
   name:"Sochi",
   country:"Russia",
   category:"Nature",
   tags:["beach","resort","Black Sea"],
   image:"https://images.unsplash.com/photo-1589794360421-9353dc25c668?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c29jaGl8ZW58MHx8MHx8fDA%3D",
   desc:"Sochi is a popular resort city on the Black Sea, known for its beaches, mild climate, and as a host city for the Winter Olympics in 2014.",
  },
];

export default rus;
