const us = [
  // USA
  {
    id: 1,
    name: "Statue of Liberty",
    country: "USA",
    category: "Landmark",
    tags: ["historical", "symbol", "UNESCO"],
    image: "https://plus.unsplash.com/premium_photo-1694475364942-b755ad751a40?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c3RhdHVlJTIwb2YlMjBsaWJlcnR5fGVufDB8fDB8fHww",
    desc: "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor, a symbol of freedom and democracy.",
  },
  {
    id: 2,
    name: "Golden Gate Bridge",
    country: "USA",
    category: "Architecture",
    tags: ["iconic", "suspension bridge", "scenic"],
    image: "https://images.unsplash.com/photo-1521747116042-5a810fda9664?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z29sZGVuJTIwZ2F0ZSUyMGJyaWRnZXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "An iconic suspension bridge connecting San Francisco to Marin County, known for its stunning views.",
  },
  {
    id: 3,
    name: "Mount Rushmore",
    country: "USA",
    category: "Monument",
    tags: ["historical", "sculpture", "national memorial"],
    image: "https://plus.unsplash.com/premium_photo-1661855590183-87806182951b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW91bnQlMjBydXNobW9yZXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "Features the sculpted heads of four U.S. presidents carved into granite in South Dakota.",
  },
  {
    id: 4,
    name: "Grand Canyon",
    country: "USA",
    category: "Nature",
    tags: ["canyon", "national park", "scenic"],
    image: "https://plus.unsplash.com/premium_photo-1669050701110-a5eb879f1b6a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z3JhbmQlMjBjYW55b258ZW58MHx8MHx8fDA%3D",
    desc: "One of the world’s most awe-inspiring natural wonders located in Arizona.",
  },
  {
    id: 5,
    name: "White House",
    country: "USA",
    category: "Government",
    tags: ["historical", "residence", "symbol"],
    image: "https://plus.unsplash.com/premium_photo-1694475311982-fa84ce0fc814?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8d2hpdGUlMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "The official residence and workplace of the President of the United States in Washington D.C.",
  },

  // Germany
  {
    id: 6,
    name: "Brandenburg Gate",
    country: "Germany",
    category: "Landmark",
    tags: ["historical", "symbol", "architecture"],
    image: "https://plus.unsplash.com/premium_photo-1694475361345-52f267ae4d92?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8QnJhbmRlbmJ1cmclMjBHYXRlfGVufDB8fDB8fHww",
    desc: "An 18th-century neoclassical monument in Berlin symbolizing peace and unity.",
  },
  {
    id: 7,
    name: "Neuschwanstein Castle",
    country: "Germany",
    category: "Architecture",
    tags: ["castle", "fairytale", "tourist attraction"],
    image: "https://images.unsplash.com/photo-1609237756221-88c4a93846b2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TmV1c2Nod2Fuc3RlaW4lMjBDYXN0bGV8ZW58MHx8MHx8fDA%3D",
    desc: "A picturesque castle in Bavaria known for its romantic architecture.",
  },
  {
    id: 8,
    name: "Cologne Cathedral",
    country: "Germany",
    category: "Architecture",
    tags: ["gothic", "UNESCO", "landmark"],
    image: "https://images.unsplash.com/photo-1617375402484-8a196422d93d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q29sb2duZSUyMENhdGhlZHJhbHxlbnwwfHwwfHx8MA%3D%3D",
    desc: "A stunning example of Gothic architecture and a UNESCO World Heritage Site.",
  },
  {
    id: 9,
    name: "Berlin Wall Memorial",
    country: "Germany",
    category: "Historical Site",
    tags: ["memorial", "history", "landmark"],
    image: "https://plus.unsplash.com/premium_photo-1678490507660-4746caa156e9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8QmVybGluJTIwV2FsbCUyME1lbW9yaWFsfGVufDB8fDB8fHww",
    desc: "A preserved section of the Berlin Wall that commemorates the division of East and West Berlin.",
  },
  {
    id: 10,
    name: "Oktoberfest",
    country: "Germany",
    category: "Festival",
    tags: ["cultural", "beer festival", "tradition"],
    image: "https://plus.unsplash.com/premium_photo-1693879090664-64a0252ef7fe?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8T2t0b2JlcmZlc3R8ZW58MHx8MHx8fDA%3D",
    desc: "The world's largest beer festival held annually in Munich celebrating Bavarian culture.",
  },

  // Australia
  {
    id: 11,
    name: "Sydney Opera House",
    country: "Australia",
    category: "Architecture",
    tags: ["iconic", "performing arts", "UNESCO"],
    image: "https://images.unsplash.com/photo-1540448051910-09cfadd5df61?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c3lkbmV5JTIwb3BlcmElMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "A multi-venue performing arts center known for its unique shell-like design.",
  },
  {
    id: 12,
    name: "Great Barrier Reef",
    country: "Australia",
    category: "Nature",
    tags: ["coral reef", "marine life", "UNESCO"],
    image: "https://images.unsplash.com/photo-1533288141458-0d76b9ba5de1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODN8fGdyZWF0JTIwYmFycmllciUyMHJlZWZ8ZW58MHx8MHx8fDA%3D",
    desc: "The world's largest coral reef system located off the coast of Queensland.",
  },
  {
    id: 13,
    name: "Uluru (Ayers Rock)",
    country: "Australia",
    category: "Natural Landmark",
    tags: ["sacred site", "geology", "UNESCO"],
    image: "https://images.unsplash.com/flagged/photo-1553779801-13e5e5f7398a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dWx1cnUoYXllcnMlMjByb2NrKXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "A massive sandstone monolith in the heart of the Northern Territory's arid 'Red Centre.'",
  },
  {
    id: 14,
    name: "Bondi Beach",
    country: "Australia",
    category: "Beach",
    tags: ["surfing", "leisure", "iconic"],
    image: "https://images.unsplash.com/photo-1548010024-af9b471c44eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fGJvbmRpJTIwYmVhY2h8ZW58MHx8MHx8fDA%3D",
    desc: "A famous beach in Sydney known for its surf culture and vibrant atmosphere.",
  },
  {
    id: 15,
    name: "Daintree Rainforest",
    country: "Australia",
    category: "Nature",
    tags: ["rainforest", "biodiversity", "UNESCO"],
    image: "https://images.unsplash.com/photo-1612712191426-54db4d88cbec?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGRhaW50cmVlJTIwcmFpbmZvcmVzdHxlbnwwfHwwfHx8MA%3D%3D",
    desc: "One of the oldest rainforests in the world located in Queensland with rich biodiversity.",
  },

  // Canada
  {
    id: 16,
    name: "CN Tower",
    country: "Canada",
    category: "Landmark",
    tags: ["tower", "observation", "iconic"],
    image: "https://images.unsplash.com/photo-1521505088417-bfc5a507f901?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fENOJTIwdG93ZXJ8ZW58MHx8MHx8fDA%3D",
    desc: "A communications and observation tower in Toronto recognized as one of the tallest freestanding structures in the world.",
  },
  {
    id: 17,
    name: "Banff National Park",
    country: "Canada",
    category: "Nature",
    tags: ["national park", "mountains", "scenic"],
    image: "https://images.unsplash.com/photo-1558818061-547b1114aa6a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmFuZmYlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D",
    desc: "Canada’s first national park located in the Rocky Mountains known for its stunning landscapes and outdoor activities.",
  },
  {
    id: 18,
    name: "Niagara Falls",
    country: "Canada",
    category: "Natural Wonder",
    tags: ["waterfall", "scenic", "tourist attraction"],
    image: "https://images.unsplash.com/photo-1533094602577-198d3beab8ea?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bmlhZ2FyYSUyMGZhbGxzfGVufDB8fDB8fHww",
    desc: "A group of three waterfalls located on the border between Canada and the USA known for their beauty and power.",
  },
  {
    id: 19,
    name: "Parliament Hill",
    country: "Canada",
    category: "Government",
    tags: ["historical site", "architecture"],
    image: "https://images.unsplash.com/photo-1691808969449-96be1eec18eb?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8cGFybGlhbWVudCUyMGhpbGx8ZW58MHx8MHx8fDA%3D",
    desc: "The seat of Canada's federal government located in Ottawa featuring stunning Gothic Revival architecture.",
  },
  {
    id: 20,
    name: "Old Quebec City",
    country: "Canada",
    category: "Historical Site",
    tags: ["UNESCO World Heritage Site"],
    image: "https://plus.unsplash.com/premium_photo-1677048148032-40f0797fb5a8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8b2xkJTIwcXVlYmVjJTIwY2l0eXxlbnwwfHwwfHx8MA%3D%3D",
    desc: "A historic district featuring cobblestone streets and well-preserved buildings from the French colonial era.",
  },
];

export default us;
